Budget App
zakiyousufi/Budget-App pull request #5
Opened 2023-02-23 17:33 UTC by zakiyousufi

### In this project I have created my budget app following these requirements 
 - Requirements [link](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md)
 - Docmantation: [video docmentation](#)

2023-02-23 19:24 UTC, danielufeli requested changes
Hi @zakiyousufi ,

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
- Nice commits messages✔️
- Clean Design✔️

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-02-23 19:24 UTC, danielufeli commented on README.md
> +## 🚀 Live Demo <a name="live-demo"></a>
- [ ] Great work your put into your video presentation, has a requirement your video should contain a highlight about a piece of the code the you find interesting and are proud of making, also the video length should me max 5mins
- [ ] You live demo link throws error 500 when you click signup, kindly fix.

2023-02-23 19:24 UTC, danielufeli commented on spec/requests/entities_spec.rb
> +    before(:example) { get group_entities_path(@group) }
- [ ] Great work you put in writing your tests, kindly check I get the error in the screenshot below when I run test.

![test-error](https://user-images.githubusercontent.com/48371156/221009390-144b5347-3dd1-47c5-883c-a43b06bf1db8.png)

2023-02-24 01:00 UTC, zakiyousufi commented
Hi @danielufeli  
Thanks for your kind review and feedback I will fix the marked points

2023-02-24 17:48 UTC, merged